apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jambonz-sbc-sip
  labels:
    app: jambonz-sbc-sip
spec:
  selector:
    matchLabels:
      app: jambonz-sbc-sip
  template:
    metadata:
      labels:
        app: jambonz-sbc-sip
    spec:
      nodeSelector:
        voip-environment: edge
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: "voip-edge"
          operator: "Exists"
          effect: "NoSchedule"
      initContainers:
        - args:
            - wait
            - --for=condition=complete
            - --timeout=300s
            - job/db-create
          image: d3fk/kubectl:v1.18
          name: db-create-wait
      containers:
        - name: drachtio
          image: drachtio/drachtio-server:0.8.12
          args: ['drachtio', '--cloud-deployment', '--loglevel', 'debug']
          envFrom:
            - secretRef:
                name: jambonz
          ports:
            - containerPort: 9022
              protocol: TCP
            - containerPort: 5060
              protocol: UDP
            - containerPort: 5060
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/drachtio.conf.xml
              name: jambonz-sbc-sip-conf
              subPath: drachtio.conf.xml
        - name: sbc-call-router
          image: jambonz/sbc-call-router:latest
          env:
            - name: HTTP_PORT
              value: "4000"
            - name: JAMBONES_INBOUND_ROUTE
              value: "127.0.0.1:4002"
            - name: JAMBONES_OUTBOUND_ROUTE
              value: "127.0.0.1:4003"
            - name: JAMBONZ_TAGGED_INBOUND
              value: "1"
            - name: ENABLE_METRICS
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: ENABLE_METRICS
            - name: JAMBONES_NETWORK_CIDR
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_NETWORK_CIDR
        - name: sbc-options-handler
          image: jambonz/sbc-options-handler:latest
          envFrom:
            - secretRef:
                name: jambonz
        - name: sbc-registrar
          image: jambonz/sbc-registrar:latest
          envFrom:
            - secretRef:
                name: jambonz
        - name: sbc-inbound
          image: jambonz/sbc-inbound:latest
          envFrom:
            - secretRef:
                name: jambonz
        - name: sbc-outbound
          image: jambonz/sbc-outbound:latest
          envFrom:
            - secretRef:
                name: jambonz
      restartPolicy: Always
      volumes:
      - name: jambonz-sbc-sip-conf
        configMap:
          name: jambonz-sbc-sip-conf
          items:
          - key: drachtio.conf.xml
            path: drachtio.conf.xml