apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jambonz

resources:
- namespace.yaml
- rbac/role.yaml
- rbac/role-binding.yaml
- db/db-create.yaml
- mysql/mysql-service.yaml
- mysql/mysql-statefulset.yaml
- redis/redis-service.yaml
- redis/redis-statefulset.yaml
- influxdb/influxdb-storageclass.yaml
- influxdb/influxdb-service.yaml
- influxdb/influxdb-statefulset.yaml
- webapp/webapp-deployment.yaml
- webapp/webapp-service.yaml
- webapp/webapp-ingress.yaml
- api-server/api-server-deployment.yaml
- api-server/api-server-service.yaml
- api-server/api-server-ingress.yaml
- sbc-sip/sbc-sip-configmap.yaml
- sbc-sip/sbc-sip-daemonset.yaml
- sbc-rtp/sbc-rtp-daemonset.yaml
- feature-server/feature-server-deployment.yaml

secretGenerator:
  - name: jambonz
    envs:
    - jambonz.env
