apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbc-inbound
  labels:
    app: sbc-inbound
  namespace: jambonz
spec:
  selector:
    matchLabels:
      app: sbc-inbound
  template:
    metadata:
      labels:
        app: sbc-inbound
    spec:
      initContainers:
        - args:
            - wait
            - --for=condition=complete
            - --timeout=300s
            - job/db-create
          image: d3fk/kubectl:v1.18
          name: db-create-wait
      containers:
        - name: sbc-inbound
          image: jambonz/sbc-inbound:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/opt/app/bin/k8s-pre-stop-hook.js"]
          envFrom:
            - configMapRef:
                name: jambonz-env
          env:
            - name: DRACHTIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: jambonz-secrets
                  key: DRACHTIO_SECRET
            - name: DRACHTIO_PORT
              value: "4000"
      terminationGracePeriodSeconds: 900
